platform :ios, ‘7.0’
pod 'GRMustache',       '~> 6.7.4'
pod 'JRSwizzle',        '~> 1.0'
pod 'UIColor-Utilities', '~> 1.0.1'
pod 'FMDB',             '~> 2.5'
pod 'MBProgressHUD', '~> 0.9'
pod 'SDURLCache', '~> 1.2'
pod 'AFNetworking', '~> 1.3.3'
pod ’FontAwesomeKit', '~> 2.2.0'